# Site settings
title: 初老騎士 - 台灣

baseurl: '/taiwan' # the subpath of your site, e.g. /blog
url: 'http://autumnal-rider.github.io' # the base hostname & protocol for your site
siteurl: 'http://autumnal-rider.github.io/taiwan'

# Build settings
markdown:            kramdown
relative_permalinks: false
permalink: "/:year/:month/:day/:title/"

pagination:          true
paginate:            8
paginate_path:       page/:num/

sass:
    sass_dir: _sass
    style:    compressed

defaults:
  -
      scope:
        path: '_posts'
        type: 'posts'
      values:
        reading_time: false
        # Meta
        show_tags: true
        show_categories: true
        # Social
        share_buttons: true
        disqus: true
